### PR TITLE
Improve Error Codes

### PR DESCRIPTION
**Pull request by embedded-creations**
This sets the iError codes for all returns with errors, some were missing

playFrame() now returns -1 if there's an error, so you can see why an interleaved GIF isn't playing properly.  I'm not sure if this is working as intended, as I'm seeing an error code of 1 set on nearly all the GIFs I tested that otherwise seem to be playing properly.

I updated the play_all_sd_files example to print errors

### CODE REVIEW

**Comment by embedded-creations** [comment]
I was focusing on the Arduino API and probably overlooked something with the C API

**Comment by embedded-creations** [comment]
Reflecting now, the changes to playFrame() are going to break most existing sketches as you used `while (gif.playFrame(false, NULL))` in your examples which will continue forever in case of an error.  I'm interested to hear what you suggest for how to recognize that `playFrame()` had an error

**Comment by tobozo** [comment]
would it make sense to use negative values in the enum ?

```C
enum {
   GIF_DECODE_ERROR = -7,
   GIF_TOO_WIDE = -6,
   GIF_INVALID_PARAMETER = -5,
   GIF_UNSUPPORTED_FEATURE = -4,
   GIF_EARLY_EOF = -3,
   GIF_NOT_A_GIF = -2,
   GIF_NO_FILE_HANDLE = -1,
   GIF_SUCCESS = 0
};
```

**Comment by bitbank2** [comment]
I did most of your changes the same way, but modified a few. To simplify the git situation, I decided to just edit and push. Please sync with my latest code and see if you're happy with the changes.

**Comment by embedded-creations** [comment]
Changes look good

I'm still getting an -1 return value and error code `GIF_DECODE_ERROR` from playFrame() on most GIFs, though they're playing properly.  (e.g. the two you tested yesterday)  Is that a bug?

```
    do
    {
      frameStatus = gif.playFrame(true, NULL);
    } while (frameStatus > 0);
    if(frameStatus < 0) {
      Serial.print("playFrame failed: ");
      Serial.println(gif.getLastError());
    }
```

```
Playing /gifs/ANIMAT~1.GIF
Successfully opened GIF; Canvas size = 64 x 64
Playing /gifs/ASTERO~1.GIF
Successfully opened GIF; Canvas size = 64 x 64
playFrame failed: 1
Playing /gifs/KARUNE.GIF
Successfully opened GIF; Canvas size = 64 x 64
playFrame failed: 1
```
animated-gifs-scorpions-16

**Comment by bitbank2** [comment]
I'll trace it with Xcode and see why that's happening - thanks for the quick test :)

**Comment by bitbank2** [comment]
I just pushed a fix. This error is occurring because in your images there is non-image data (comments and other stuff) after the last frame. This fools the playFrame() logic into trying to play a frame which isn't there and then hits an error.

**Pull request closed without merging**
