### PR TITLE
improve comments and add possibilty to set MAX_WIDTH and FILE_BUF_SIZ…

### PR DESCRIPTION
**Pull request by jrahlf**
1. separate defines into simple and expert options
2. simple options (`MAX_WIDTH`) can be set via #define
3. improve comments, I think some were outdated

### CODE REVIEW

**Comment by bitbank2** [comment]
My comments at lines 48-53 are still correct. You can reduce the palette size and max code size if you work with small images. If the total number of symbols to decode is less than the max code size, you can safely reduce the max code size.

**Comment by jrahlf** [comment]
But then how do I calculate the required max code size for a given image size? I think that would be a more helpful comment.

**Comment by bitbank2** [comment]
This is one of the problems with your issues and merge request. You're trying to make changes to my library that you don't fully understand and asking me to teach you how it works along the way. If you want to continue this discussion, you'll need to pay me for consulting time.

**Comment by jrahlf** [comment]
Sure I am costing you time here, but I also try to improve the library for me and everyone else.
But yeah, if you want to market your services then comments like 

> // a 128x32 display will not need a max code size of 12 nor a palette with 256 entries

are the way to go.

**Pull request closed without merging**
