### PR TITLE
Update gif.inl

### PR DESCRIPTION
**Pull request by AnatolShiro**
Increases execution speed by few percent

### CODE REVIEW

**Comment by bitbank2** [comment]
I just tested this on the ESP32-S3 and didn't see any improvement in speed. Where are you seeing a speed improvement?

**Comment by AnatolShiro** [comment]
> I just tested this on the ESP32-S3 and didn't see any improvement in speed. Where are you seeing a speed improvement?

Hello. I tested is with stm32f429 (cortex-m4f) 168 MHz. It takes to decode badgers gif from flash 56.4 ms and with this change 53.05 ms.  I removed 
`memset(&giftabs[cc], LINK_UNUSED, 4096 - cc);`
from init_codetable:
and added conditionally to main decode loop:

```
if (nextcode < nextlim) // for deferred cc case, don't let it overwrite the last entry (fff)
{
    giftabs[nextcode] = oldcode;
    gifpels[PIXEL_FIRST + nextcode] = gifpels[PIXEL_FIRST + oldcode];
    if (giftabs[code] == LINK_UNUSED) /* Old code */
        gifpels[PIXEL_LAST + nextcode] = gifpels[PIXEL_FIRST + oldcode];
    else
        gifpels[PIXEL_LAST + nextcode] = gifpels[PIXEL_FIRST + code];
}
else
{
 if(nextcode < 4096) giftabs[nextcode] = LINK_UNUSED;
}
```

**Comment by vietTQ123** [comment]
I want to move the gif to the point I want to place, what should I do? Please help

**Comment by bitbank2** [comment]
> I want to move the gif to the point I want to place, what should I do? Please help

Your question has nothing to do with this issue and is already explained in several of the example sketches.

**Pull request closed without merging**
